module.exports = [
  'Look into the eyes of a chicken and you will see real stupidity. It is a kind of bottomless stupidity, a fiendish stupidity.\n They are the most horrifying, cannibalistic and nightmarish creatures in the world.',
  'In the face of the obscene, explicit malice of the jungle, which lacks only dinosaurs as punctuation, I feel like a half-finished, poorly expressed sentence in a cheap novel.',
  'Facts do not convey truth. That\'s a mistake. Facts create norms, but truth creates illumination.',
  'I believe the common denominator of the universe is not harmony; but chaos, hostility and murder.',
  'If you’re purely after facts, please buy yourself the phone directory of Manhattan. It has four million facts, but it doesn\'t illuminate.',
  'Civilization is like a thin layer of ice upon a deep ocean of chaos and darkness.',
  'That man is a head taller than me. That may change. ',
  'You are all wrong.',
  'Together, I said, we shall boil fire and stop fish.',
  'I shouldn\'t make movies anymore. I should go to a lunatic asylum.',
  'I like to direct landscapes just as I like to direct actors and animals.',
  'Do you not then hear this horrible scream all around you that people usually call silence?',
  '🌲 Truth itself wanders through the forests.',
  'What would an ocean be without a monster lurking in the dark?\n It would be like sleep without dreams.',
  'Every man should pull a boat over a mountain once in his life.',
  'Those who read own the world; those who watch television lose it.',
  'I am someone who takes everything very literally. I simply do not understand irony, a defect I have had ever since I was able to think independently.',
  'Nothing I have witnessed, from lava to crustacean, assailed me liked the caked debris haunting that small plastic soap hammock in the smaller of the bathrooms.\n Nausea is not a sufficient word.',
  'Tell me about an encounter with a squirrel.',
  '...we have to declare a holy war against what we see every single day on television.',
  'The world reveals itself to those who travel on foot.',
  'A fairly young, intelligent-looking man with long hair asked me whether filming or being filmed could do harm, whether it could destroy a person.\n In my heart the answer was yes, but I said no.',
  'I never planned my career in steps. It\'s all coming at me like burglars in the night.',
  'I love nature but against my better judgment.',
  'Never wallow in your troubles; despair must be kept private and brief.',
  'Of course, as a German, I wouldn\'t like to tell the American people how to handle their criminal justice.',
  'If an actor knows how to milk a cow, I always know it will not be difficult to be in business with him.',
  '🌋 Nature is monumentally indifferent.',
  'I travel without barely any luggage. Just a second set of underwear and binoculars and a map and a toothbrush.',
  'We have to articulate ourselves. Otherwise we would be cows in the field.',
  'If you want to do a film, steal a camera, steal raw stock, sneak into a lab and do it!',
  'I think psychology and self-reflection is one of the major catastrophes of the twentieth century.',
  'Ambition is to be the fastest runner on this planet, to be the first on the South Pole, which is a grotesque perversion of ambition.\n It\'s an ego trip, and I\'m not on an ego trip. I don\'t have ambitions; I have a vision.',
  'I see planets that don\'t exist and landscapes that have only been dreamed.',
  'I think I would be a good villain in a James Bond movie. They were fairly weak, the last half-dozen of villains in James Bond movies were not that convincing.',
  'I could not become an American citizen. I would not like to become a citizen of a country that has capital punishment.',
  'It seems odd, but people who see my films normally take them in in a deeper way than you would actually watch a film, let\'s say The Terminator or whatever.',
  'There\'s this kind of strange mythology about me in the media because I\'ve done unusual things.',
  'I\'ve dwelled among the humans. Their entire culture is built around their penises. It\'s funny to say they are small, it\'s funny to say they are big. I\'ve been at parties where humans have held bottles, pencils and thermoses in front of themselves and called out, "Hey, look at me! I\'m Mr. So-And-So Dick! I\'ve got such-and-such for a penis!" I never saw it fail to get a laugh.'
]
